import {Inter} from "next/font/google";
import "./globals.css";
import Navbar from "@/app/_components/shared/Navbar/Navbar";
import Footer from "@/app/_components/shared/Footer/Footer";
import { AntdRegistry } from '@ant-design/nextjs-registry';

const inter = Inter({subsets: ["latin"]});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <AntdRegistry>
            <Navbar/>
            <main>
                {children}
            </main>
            <Footer/>
        </AntdRegistry>
        </body>
        </html>
    );
}
